A lot of refactor
YutoMaeda1209/PrimitierOnlineMod pull request #1
Opened 2024-09-23 09:12 UTC by CREAsTIVE

Don't be shy to point out things you don't like. I can return any change individually if you want

2024-09-24 09:53 UTC, YutoMaeda1209 commented
Have you set up a local server and checked to see if you can connect?

2024-09-26 06:17 UTC, CREAsTIVE commented
@YutoMaeda1209 Yes, everything works fine

2024-09-26 07:14 UTC, CREAsTIVE commented
Fixed now!

2024-09-26 07:16 UTC, CREAsTIVE commented
Please notice, that required variables rn is:
```
LiteNetLib.dll
MessagePack.Annotations.dll
MessagePack.dll
System.Security.Permissions.dll - requires for desirealization through Newtonsoft.json
```

2024-09-27 03:34 UTC, YutoMaeda1209 requested changes
Sorry for the delay! I have reviewed your pull request, please change it. ( ᴗ ᴗ )

2024-09-27 03:34 UTC, YutoMaeda1209 commented on Server/Managers/Network.cs
> +                                false
Replace false with Program.Settings.DayNightCycle.

2024-09-27 03:34 UTC, YutoMaeda1209 commented on Server/Managers/Network.cs
Please tell me why you changed from a static class to a regular class!

2024-09-27 05:41 UTC, CREAsTIVE commented on Server/Managers/Network.cs
Static types are anti-pattern. What if you want to launch more than one world/server at once? For example, allow players to create their own worlds on a single server.

2024-09-27 05:47 UTC, CREAsTIVE commented on Server/Managers/Network.cs
+ if you really want to keep ONLY ONE object of that class, you can create private constructor with static Instance field

2024-09-27 06:26 UTC, CREAsTIVE commented on Client/Client.csproj
> +  <ItemGroup>
@YutoMaeda1209 Bad idea imo. Client will require `Shared.dll` inside `UserLibs` folder. But if you sure about this tell me, and i will do it

2024-09-27 06:29 UTC, CREAsTIVE commented on Client/DataTypes/DataConverter.cs
To what?

2024-09-27 06:31 UTC, CREAsTIVE commented on Client/Client.csproj
> +  <ItemGroup>
I also was thinking about ilmerge or something similar, but that will overcompilcate things. I have one idea: put everything from `Shared` to `Client`, and add reference to it from `Server`, but also didn't sure about that solution

2024-09-27 07:43 UTC, YutoMaeda1209 commented on Client/Client.csproj
> +  <ItemGroup>
I see!So that's how it was.Then let's go with the way it is.

2024-09-27 08:20 UTC, YutoMaeda1209 commented on Client/DataTypes/DataConverter.cs
Sorry for the lack of words. If the argument type is SVector3, the name should be sVector3, and if it is STransform, the name should be sTransform.

2024-09-27 10:45 UTC, CREAsTIVE commented on Server/Managers/Network.cs
@YutoMaeda1209 Thats fair. I will roll that change back

2024-09-27 10:50 UTC, CREAsTIVE commented
@YutoMaeda1209 Done

2024-09-27 12:53 UTC, YutoMaeda1209 approved these changes

2024-09-27 12:55 UTC, YutoMaeda1209 commented
LGTM! Sorry for all the problems with my first review. Thank you for the pull request!

2024-09-27 12:56 UTC, merged